If:
  PathMatch: .*\.c
CompileFlags:
    Add: [-Wall, -Wextra, -pedantic, -Wno-deprecated-declarations, -O3, -std=gnu99]
    Compiler: gcc
---
If:
  PathMatch: .*\.cpp
CompileFlags:
    Add: [-Wall, -Wextra, -pedantic, -O3, -std=c++17]
    Compiler: g++
